# Generated by Django 3.1.4 on 2020-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(default='', max_length=20)),
                ('asset_name', models.CharField(default='', max_length=20)),
                ('asset_quantity', models.IntegerField(default=0)),
                ('asset_price', models.FloatField(default=0)),
            ],
        ),
    ]
